# -*- coding: utf-8 -*-
"""generate attack pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183qOUKyqrzRiespj-EMeymOz3JwSFWDv

# Markov pattern
"""

import copy
import numpy as np
def get_attack_list(graph_num,frame_num):
    attack_list = []
    transition_matrix_list = [[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2],[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2]]
    for frame in range(frame_num):
        attack_list_frame = []
        for group in range(graph_num):
            attack_list_frame.append(1)
        attack_list.append(attack_list_frame)
    p_q = [0.25,0.25,0.25,0.25]

    for frame in range(frame_num):
        if frame == 0:
            p0 = np.array(p_q)
        else :
            p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list) #?
        attack_list_copy[frame][index] = 0
    return attack_list_copy

attack_list_copy = get_attack_list(4,4000)
# print(attack_list)
filename = 'markov_attack_list_0713_2022_1.txt'
np.savetxt(filename,attack_list_copy)
print(attack_list_copy)

"""# generate inverse attack"""

import copy
import numpy as np
def get_attack_list(graph_num,frame_num):
    attack_list = []
#     transition_matrix_list = [[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2],[0.35,0.15,0.35,0.15],[0.3,0.2,0.3,0.2]]
    transition_matrix_list = [[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35],[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35]]
    for frame in range(frame_num):
        attack_list_frame = []
        for group in range(graph_num):
            attack_list_frame.append(1)
        attack_list.append(attack_list_frame)
    p_q = [0.25,0.25,0.25,0.25]

    cut_frame = int(frame_num/2)-1000
    for frame in range(cut_frame):
        if frame == 0:
            p0 = np.array(p_q)
        else :
            p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list)
        attack_list_copy[frame][index] = 0

#     transition_matrix_list = [[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35],[0.2,0.3,0.2,0.3],[0.15,0.35,0.15,0.35]]
    transition_matrix_list = [[0.35,0.15,0.45,0.05],[0.3,0.2,0.4,0.1],[0.35,0.15,0.45,0.05],[0.3,0.2,0.4,0.1]]
    cut_frame_inverse = frame_num - cut_frame
    for frame in range(cut_frame_inverse):
        frame = frame+ 2000
        p0 = np.array(transition_matrix_list[index])
        index = np.random.choice([0,1,2,3], p = p0.ravel())
        print(frame,index)
        attack_list_copy = copy.copy(attack_list)
        attack_list_copy[frame][index] = 0

    return attack_list_copy

attack_list_copy = get_attack_list(4,6000)
# print(attack_list)
filename = 'markov_attack_list_0713_2022_4T.txt'
np.savetxt(filename,attack_list_copy)
print(attack_list_copy)

frame_num = 8000
print(frame_num/2)

filename = 'dataset/markov_attack_list_0713_2022_1.txt'
# filename = 'dataset/adaptive_attack_list_0713_2022_d1.txt'
import numpy as np
attack_list =  np.loadtxt(filename)
attack_list.tolist()
print(type(attack_list))
a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(1000,1600):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)

# filename = 'dataset/markov_attack_list_0713_2022_1T.txt'
attack_list =  np.loadtxt(filename)
attack_list.tolist()
print(type(attack_list))
a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(6000):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)

import numpy as np
filename = 'dataset/markov_attack_list_0713_2022_1.txt'
attack_list =  np.loadtxt(filename)
attack_list.tolist()
attack_cut1_3 = attack_list[0:3000]
print(attack_cut1_3)
filename = 'markov_attack_list_0713_2022_1_cut13.txt'
np.savetxt(filename,attack_cut1_3)

a0 = 0
a1 = 0
a2 = 0
a3 = 0
# attack_list[:,0].count(0)
for i in range(3000):
    if attack_list[i][0] == 0:
        a0 = a0 + 1
    if attack_list[i][1] == 0:
        a1 = a1 +1
    if attack_list[i][2] == 0:
        a2 = a2 +1
    if attack_list[i][3] == 0:
        a3 = a3 +1
print(a0,a1,a2,a3)